# Placeholder for OpenAPI (Swagger) documentation.
# A full implementation would describe all API endpoints, models, and security schemes.
openapi: 3.0.0
info:
  title: Live Streaming Platform API
  version: 1.0.0
  description: API for managing authentication, rooms, and chat for the real-time collaboration platform.

paths:
  /api/v1/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully

  /api/v1/auth/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful, returns JWT token